#!/bin/bash

[ -n "$PS1" ] \
    && . ~/.bash_profile


# SBT options
export SBT_OPTS="-Xmx4G -XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled -Xss2M"

[ -f ~/.fzf.bash ] && source ~/.fzf.bash
eval '
_direnv_hook() {
  local previous_exit_status=$?;
  eval "$("/usr/bin/direnv" export bash)";
  return $previous_exit_status;
};
if ! [[ "${PROMPT_COMMAND:-}" =~ _direnv_hook ]]; then
  PROMPT_COMMAND="_direnv_hook${PROMPT_COMMAND:+;$PROMPT_COMMAND}"
fi'


complete -C /usr/bin/terraform terraform
